# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT:                 ${LOG_LEVEL_ROOT}
    org.hibernate.SQL:    ${LOG_LEVEL_HIBERNATE_SQL}
    com.banking.threeom:  ${LOG_LEVEL_3OM}

management:
  metrics:
    export:
      prometheus:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:      ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Replace by 'prod, faker' to add the faker context and have sample data loaded in production
  liquibase:
    contexts: prod

server:
  port:                     ${SERVER_PORT} # 8080
  shutdown:                 graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled:                ${SERVER_ENABLE_COMPRESSION} # true
    mime-types:             ${SERVER_MIME_TYPES} # text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size:      ${SERVER_MIN_RESPONSE_SIZE} # 1024