version: '3.8'

services:

  banking_3om-sonar:
    image: sonarqube:9.6.0-community
    # Authentication is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete sonar.forceAuthentication variable or set sonar.forceAuthentication=true
    environment:
      - sonar.forceAuthentication=false
    ports:
      - 127.0.0.1:9001:9000
